services:
  nixiesearch:
    image: nixiesearch/nixiesearch:0.1.1-amd64
    ports:
      - "8080:8080"
    volumes:
      - "./data:/data"
      - "./indexes:/indexes"
    command:
      - "standalone"
      - "-c"
      - "/data/config-local.yml"