services:
  nixiesearch:
    image: nixiesearch/nixiesearch:0.6.2-M1-amd64
    ports:
      - "8080:8080"
    volumes:
      - "./data:/data"
    command: ["standalone", "-c", "/data/config.yml"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 1s
      retries: 100
      start_period: 4s
      start_interval: 5s
  load_data:
    image: curlimages/curl:latest
    depends_on:
      nixiesearch:
        condition: service_healthy
    volumes:
    - "./data:/data"
    command: "curl -v -XPOST -d @/data/movies.jsonl http://nixiesearch:8080/v1/index/movies"
